# Generated by Django 4.2.2 on 2023-06-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_item_brand_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
