# Generated by Django 4.2.2 on 2023-06-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.FloatField(default=None, null=True),
        ),
    ]
