# Generated by Django 4.2.2 on 2023-06-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slugName',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=75),
        ),
    ]
