# Generated by Django 4.2.2 on 2023-06-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_item_slugname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slugName',
            field=models.CharField(default="<slotwrapper'__str__'of'object'objects>", max_length=75),
        ),
    ]
