# Generated by Django 4.2.2 on 2023-06-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_item_slugname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slugName',
        ),
    ]
