# Generated by Django 4.2.2 on 2023-07-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_review_r_build_quality_review_r_cosmetics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='i_build_quality',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='i_cosmetics',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='i_playability',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='i_sound',
            field=models.FloatField(default=None, null=True),
        ),
    ]
