# Generated by Django 4.2.2 on 2023-07-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_item_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='i_build_quality',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='i_cosmetics',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='i_playability',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='i_sound',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
