# Generated by Django 4.2.2 on 2023-07-13 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0023_alter_review_approves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='approves',
            field=models.ManyToManyField(related_name='review_approves', to=settings.AUTH_USER_MODEL),
        ),
    ]
